# Generated by Django 6.0.2 on 2026-03-23 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='social_link',
            field=models.URLField(blank=True, help_text='Optional: Add a link to read more (e.g., Quora)', null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='blog_body',
            field=models.TextField(),
        ),
    ]
