# Generated by Django 6.0.2 on 2026-02-09 20:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0002_sociallink_alter_about_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator('^\\+?\\d{9,15}$')])),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('country', models.CharField(default='Nigeria', max_length=100)),
                ('tribe', models.CharField(default='Yoruba', max_length=100)),
                ('is_yoruba', models.BooleanField(default=True)),
                ('passport_id_number', models.CharField(max_length=50)),
                ('passport_id_type', models.CharField(choices=[('passport', 'Passport'), ('national_id', 'National ID'), ('voters_card', 'Voters Card'), ('other', 'Other')], max_length=50)),
                ('passport_id_image', models.ImageField(upload_to='uploads/passports/')),
                ('occupation', models.CharField(blank=True, max_length=100)),
                ('education', models.CharField(blank=True, max_length=100)),
                ('reason_for_joining', models.TextField(blank=True)),
                ('date_applied', models.DateTimeField(auto_now_add=True)),
                ('is_verified', models.BooleanField(default=False)),
            ],
        ),
    ]
